### ISSUE TITLE
About PregnancyPlus trouble

### ISSUE THREAD

**Issue by Kamisato100** [thojmr/KK_PregnancyPlus#10]
I don't understand why you removed the clothing mix mode switch (the V1/V2 drop-down bar), it is very practical and convenient, and can help me reduce many clothing wear problems. I feel uncomfortable that the new version PregnancyPlus does not have this option, I hope you can restore it if possible.

**Comment by thojmr** [comment]
The idea was to eventually phase out V1 since V2 was better at preserving clothing thickness, and reducing clipping.  However if you notice worse results with V2, let me know which zipmods.  I can take a look unsing an older version of Preg+.

**Comment by Kamisato100** [comment]
Thank you. I found that the problem of the new version mainly lies in close-fitting clothes (such as some swimsuits) and multi-layer clothes (such as maid's clothes with aprons). The clothes/models on the bottom layer will wear through the models on the upper layer, resulting in poor appearance, while the old V1 model can effectively solve part of the problem and make the clothes look more fitting.

**Comment by Kamisato100** [comment]
I always think it's better to give the user an extra choice, even though V2 mode does work well most of the time, there are still individual pieces that don't fit as well, and V1 mode often helps.  So I still recommend that you restore the V1/V2 mode option.

**Comment by Kamisato100** [comment]
I always think it's better to give the user an extra choice, even though V2 mode does work well most of the time, there are still individual pieces that don't fit as well, and V1 mode often helps.  So I still recommend that you restore the V1/V2 mode option.

**Comment by Kamisato100** [comment]
I even think, if that's possible, you could consider allowing players to choose V1/V2 for each outfit individually.

**Comment by thojmr** [comment]
My latest release might help, but its limited to KKS, HS2, and AI.  [v6.4](https://github.com/thojmr/PregnancyPlus/releases)
It allows you to offset each clothing item separately.  Should give better control for tight clothing.
