### ISSUE TITLE
[HS2] Clipping on half state vanilla tops after version 6.8

### ISSUE THREAD

**Issue by LeonardZasquero** [thojmr/KK_PregnancyPlus#12]
some obvious clipping on half state on vanilla game tops, it was fixed on 6.7 and 6.8 but after those version, the clipping is back again
![StudioNEOV2_v23rhDTB82](https://user-images.githubusercontent.com/105122529/167264069-7681d022-e6c2-4eab-a6b9-532c2b1d84f0.jpg)
![StudioNEOV2_v23rhDTB821](https://user-images.githubusercontent.com/105122529/167264071-98288b20-b4d5-4c65-b31a-6dc123dc4d47.jpg)
.

**Comment by thojmr** [comment]
Thanks for the report!  I'm hoping this was just fixed with the v7.1 release.  I went through a handfull of vanilla tops just now and didn't notice anything.

Can you give v7.1 a quick try and let me know if it fixed the issue for you?  If it's still not fixed, just let me know the name of that specific top and I can dig further.

**Comment by LeonardZasquero** [comment]
sorry for late reply i was a bit busy
seems like its not fixed yet on 7.1 and 7.2, the top that problematic are Blouse, Maid Dress and Open Concierge Suit. only the half states.

it was all fixed on 6.7 and 6.8 but after it the clipping is back.

**Comment by thojmr** [comment]
So far I haven't been able to trigger this bug.  If you want to send me the character card or scene to test with, here or on discord feel free `thojm#6949`  
It could have something to do with the specific uncensor you are using, but It's hard to say without the card data.

**Comment by LeonardZasquero** [comment]
i tried with all uncensor and even different chara, seems weird tho if its only me. but ill send you the card.

**Comment by LeonardZasquero** [comment]
7.3 fixed the issue, thanks for all the support @thojmr
