### ISSUE TITLE
about update 

### ISSUE THREAD

**Issue by poor-girl** [thojmr/KK_PregnancyPlus#14]
When the version is upgraded from HS2_PregnancyPlus.v6.13 update to HS2_PregnancyPlus.v7.8, the plugin does not work anymore。
BepInex version is BepInEx_x64_5.4.21.0  
HS2_BepisPlugins_r19.1
BepInEx.ConfigurationManager_v17.1

**Comment by thojmr** [comment]
I haven't heard anyone else mentioning any issues with the plugin, I'll assume it was a one off problem, or plugin incompatibilty
