### ISSUE TITLE
Reloading card still required? (HS2)

### ISSUE THREAD

**Issue by roy12-meh** [thojmr/KK_PregnancyPlus#3]
Hi. 

First I'd like to tell you I love this plugin, but I didn't want the issue to get lost in Discord so I'd rather create an issue.

Now onto the issue.

**Issue:**
I thought the data got lost, but it turns out it loads if I load the card manually with the load button (instead of the first load the maker does), my bad.

**Steps to reproduce:**

1) Have a girl with a belly.
2) Click Play
3) Click Manage Characters
4) Click Edit Groups
5) Click on your girl
6) Click on Change Appearance
7) Make any changes
8) Click on the exit icon
9) Click on Save and quit

Alternatively, you can take any girl without any pregnancy data from the same place, set any pregnancy sliders to her, save and quit, and once loading that card you'll notice the belly is gone.

**Expected result:**
Girl loads with her pregnancy data without having to manually load the card.

**Actual result:**
Girl loads without belly, requires reloading the card.

**Comment by thojmr** [comment]
Good catch, Looks like when editing a character via the "Play" button, the changes are not visully loading.  But when using "Create" from the main menu, they do.  I can see that the card data does persist, I just need to figure out why the changes are not being triggered in that case.  

Thanks

**Comment by thojmr** [comment]
Alright I think [v1.19](https://github.com/thojmr/KK_PregnancyPlus/releases) will fix this.  Turns out the initially loaded character just wouldn't have any sliders applied because it was trying to set them before Maker was done loading.

Let me know if it works for you.

**Comment by roy12-meh** [comment]
Hi.

Thanks a lot! I tried the fix today. It does work, but only the first time you load the maker.
Let me do a step by step:

1. Have a girl with a belly.
2. Click Play
3. Click Manage Characters
4. Click Edit Groups
5. Click on your girl
6. Click on Change Appearance
7. She'll load with her belly without issues.
8. Close the editor. Save or not, doesn't change the outcome of the next steps.
9. Click on your girl again
10. Click on Change Appearance
11. The girl loads without a belly
12. Load her manually
13. Her belly loads
14. Any repeats from steps 8 to 11 display the same issue, the girl loads without her pregnancy+ settings, they only load if manually loaded.

I tried checking the log for any issues the moment I loaded the card, but I see no error messages or anything related to Pregnancy+

**Comment by thojmr** [comment]
Ohh yea, the second time Maker loads, some of the slider references are lost :(
This will take a little more effort to fix, but it's on my fix list now.  Thanks

**Comment by thojmr** [comment]
Alright found a fix for the issue, give [v1.21](https://github.com/thojmr/KK_PregnancyPlus/releases) a try.

**Comment by roy12-meh** [comment]
Great! That fixed it. Thank you!
