### ISSUE TITLE
When doing two girls at the same time, second girl may not load pregnancy

### ISSUE THREAD

**Issue by roy12-meh** [thojmr/KK_PregnancyPlus#4]
Hey.

I found another issue, this time is gameplay related.

First I want to specify that this only seems to happen by chance, or maybe only the first time you attempt it, so it might be difficult to reproduce this.

Whenever you choose two girls to have fun with, they will both load their pregnancy in the select screen without issues.
However, once you get into the scene itself, there's a chance that the second girl won't load her pregnancy settings

**Steps to reproduce:**

1. Have 2 girls with pregnancy settings.
2. Click on Play.
3. Make sure both girls are in the same group.
4. Click Leave room.
5. Click Call a Girl.
6. Click Select 1st Girl.
7. Select the first pregnant girl to have fun with.
8. Click Select 2nd Girl.
9. Select the second pregnant girl to have fun with (both will have loaded her pregnancy settings just fine up to this point)
10. Click Engage in fun (have to censor that word, don't know about Github's policies)
11. Select a map and then click on Start in this map.
12. By default, the first girl will have loaded. Her pregnancy shows up.
13. Go and select one of the 2 females 1 male scenes.
14. At this point, you either get only the 1st girl loading her pregnancy settings and the 2nd one doesn't, or you get both of them to load their pregnancy settings. The first time I attempted this, I had the 2nd girl not load her pregnancy settings. I finished the scene, then tried again to write down the steps. Second time both girls loaded their pregnancy settings.

Like always, thanks a lot for this plugin.

**Comment by thojmr** [comment]
Thanks, I'll check it out.

**Comment by thojmr** [comment]
Alright, when you get a chance see if [v1.22](https://github.com/thojmr/KK_PregnancyPlus/releases) fixed this issue for you.

**Comment by roy12-meh** [comment]
Hey, sorry for not answering yesterday, been busy. 

Definitely seems to work, I entered and finished a scene twice and twice did it work without issues.

Thanks a lot!
