### ISSUE TITLE
Only affects clothes.

### ISSUE THREAD

**Issue by jctneko** [thojmr/KK_PregnancyPlus#5]
KK_Pregnancy is work fine, but Plus is only work on clothes.
![image](https://user-images.githubusercontent.com/79409960/108628704-56cb9b80-7497-11eb-8eb9-4fff21d354f8.png)
[output_log.txt](https://github.com/thojmr/KK_PregnancyPlus/files/6017911/output_log.txt)

**Comment by thojmr** [comment]
I assume you are in Maker?  Do you know the exact steps that caused this?  Because I can't seem to get it to happen on my end.

**Comment by jctneko** [comment]
Yes i'm in character maker.
I found the problem is because the uncensor file "oo_base.unity3d" in kplug
, probably can’t be used at the same time for now.

**Comment by thojmr** [comment]
Ohh yea, if its one of the non kplug uncensors it should be fine, but there's no guarantee when it comes to kplug uncensors.

**Comment by jctneko** [comment]
Of course, great plug-in
thanks!
