### ISSUE TITLE
Koikatsu story mode configuration question

### ISSUE THREAD

**Issue by narkafh** [thojmr/KK_PregnancyPlus#9]
Hi, I got this installed and working with the KK_Pregnancy mod. Is there anyway to configure them together to get the the KK_Pregnancy story mode 40 week progressional pregnancy & optional inflation mechanics, but using this mod's improved belly visuals? After messing around with your mod for a little, it seems like you can only adjust the belly manually with key binds and sliders.

**Comment by thojmr** [comment]
Not at the moment, but it has been requested a few times.  
I have been thinking about adding this option, but it would require some form of option in KK_Pregnancy to rely on KK_Preg+ belly shape.  But it's a possibility ill do some research on.

**Comment by thojmr** [comment]
Well, it turned out way easier to implement than I thought it would be.  Ill upload a new release sometime soon.

**Comment by narkafh** [comment]
Awesome, I can't wait!

**Comment by thojmr** [comment]
Feature release [here v4.1](https://github.com/thojmr/KK_PregnancyPlus/releases/tag/4.1)
Let me know if you run into any issues.

**Comment by narkafh** [comment]
Wow, that was quick! Thanks a ton. I'll let you know if I come across anything.
